<?php

function customlogo_menu() {
    
    $items['customlogo'] = array(
	'title' => '',
	'description' => 'custom logo',
	'page callback' => 'customlogo_main',
	'access callback' => true,
	'type' => MENU_CALLBACK,
    );

    $items['admin/settings/customlogo'] = array(
	'title' => 'Custom settings for logo',
	'description' => t('Settings to control the display of the logo and section name.'),		
	'page callback' => 'drupal_get_form', 
	'page arguments' => array('customlogo_settings_form'),
	'access callback' => 'user_access',
	'access arguments' => array('administer content types'), 
	'type' => MENU_NORMAL_ITEM,
    );

    return $items;

}



function customlogo_settings_form() {
    
    $form['customlogo_info'] = array(
        '#type' => 'markup',
        '#value' => '<div>' . t('This module allows for custom configuration of the site logo by overriding the default behavior and linking the logo to the URL given here. It also determines whether or not the site name should be shown next to the logo. The logo it uses is the one uploaded in the theme configuration section. Please see that admin page to upload it.') . '</div>',
    );
    
     $form['customlogo_url'] = array(
        '#type' => 'textfield',
        '#title' => t('Logo URL'),
        '#description' => t('The url that the logo links to.'),
        '#default_value' => variable_get('customlogo_url', ''),
        '#size' => 80,
    );

     $form['customlogo_show_name'] = array(
        '#type' => 'checkbox',
        '#title' => t('Show site name next to logo?'),
        '#description' => 'Check this box if the site name should be shown to the right of the logo.',
        '#default_value' => variable_get('customlogo_show_name', '1'),
    );


    $form['#submit'][] = customlogo_settings_form_submit;

    return system_settings_form($form);

}





function customlogo_main() {
    $logo_link = variable_get('customlogo_url', '');
    $output = 'The custom logo link is ' . $logo_link . '<br/>';
    $output .= 'Show site name? ' . variable_get('customlogo_show_name', 'not defined');
    return $output;
}